USE url_shortener;

-- Replace the bcrypt hashes below with hashes generated by your application.

INSERT INTO users
(
    first_name,
    last_name,
    email,
    password_hash,
    role,
    is_verified,
    is_active,
    last_login_at
)
VALUES
(
    'Admin',
    'User',
    'admin@example.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    'ADMIN',
    TRUE,
    TRUE,
    NOW()
),
(
    'John',
    'Doe',
    'john@example.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    'USER',
    TRUE,
    TRUE,
    NOW()
),
(
    'Jane',
    'Smith',
    'jane@example.com',
    '$2b$12$REPLACE_WITH_BCRYPT_HASH',
    'USER',
    TRUE,
    TRUE,
    NOW()
);